builds:
  - id: default
    ldflags: -s -w -X github.com/destanyinside/mefi/cmd.version={{.Version}}
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - "386"

before:
  hooks:
    - go mod download

release:
  # publish github releases as draft, so a human can check and validate
  draft: true

archives:
  - id: mefi
    format: binary
    builds: [default] # publish easy to curl flag files rather than tarballs

changelog:
  filters:
    exclude:
      - Merge

dockers:
  # TODO when stable, use "docker_manifest" to publish multi-arch images
  - image_templates:
      - "destanyinside/mefi:{{ .Tag }}"
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    skip_push: false
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
