---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mefi.fullname" . }}
  namespace: {{ include "mefi.namespace" . }}
  labels:
  {{- include "mefi.labels" . | nindent 4 }}
  {{- with .Values.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "mefi.selectorLabels" . | nindent 6 }}
  {{- with .Values.deploymentStrategy }}
  strategy:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  template:
    {{- include "mefi.podTemplate" . | nindent 4 }}
