---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "mefi.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "mefi.serviceAccountName" . }}-local
  namespace: {{ include "mefi.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mefi.fullname" . }}-local-clusterrole
  labels:
    {{- include "mefi.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs:
      - get
      - list
      - watch
      - delete
      - update
{{- with .Values.rbac.extraClusterRoleRules }}
{{- toYaml . | nindent 2 }}
{{- end}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mefi.fullname" . }}-local-clusterrolebinding
  labels:
    {{- include "mefi.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  kind: ClusterRole
  name: {{ include "mefi.fullname" . }}-local-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "mefi.serviceAccountName" . }}-local
    namespace: {{ include "mefi.namespace" . }}