---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: admin
  annotations:
    kubernetes.io/service-account.name: admin
type: kubernetes.io/service-account-token
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-admin
subjects:
  - kind: ServiceAccount
    name: admin
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
