# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.29'
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
    - name: Upload
      uses: actions/upload-artifact@v3.1.3
      with:
        name: mefi
        path: ./mefi
